In [2]:
from pathlib import Path
from dotenv import load_dotenv
import re
import os
import smtplib
import pymongo
import warnings
import numpy as np
import pandas as pd
import datetime as dt
import seaborn as sns
from datetime import datetime
import matplotlib.pyplot as plt
from flatten_json import flatten
from google.cloud import bigquery
from bson.objectid import ObjectId
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
env_path = Path('/home/aurora') / '.env'
load_dotenv(dotenv_path=env_path)
cursor = pymongo.MongoClient("mongodb://" + os.environ['user'] + ':' + 
                             os.environ['pass'] + '@' + os.environ['db1']  + "/?authSource=" + 
                             os.environ['dbname'])

In [3]:
end = dt.datetime.today() - dt.timedelta(1)
end = end.replace(hour=18, minute=30, second=0, microsecond=0)
start = end - dt.timedelta(1)
print(start, end, end - start)

2019-06-24 18:30:00 2019-06-25 18:30:00 1 day, 0:00:00

In [4]:
aw = []
c_users = cursor.superstars.users
for documents in c_users.find({},{'app_data'}): 
    aw.append(documents)

dic_flattened = [flatten(d) for d in aw]
users = pd.DataFrame(dic_flattened)

In [5]:
users = users[['_id','app_data_0_app_kind']]
users = users.fillna(1)
tgpl_users = users[users['app_data_0_app_kind']=='2']
del users

In [29]:
print('Querying Collectables Logs Table')
c_ucl = cursor.superstars.user_collectables_logs
aw = []
for documents in c_ucl.aggregate([{'$sort' : {'_id' : -1}}, 
                                  {"$match" : {"type" : "HARD_CURRENCY"}}, 
                                    {"$match" : {"user" : ObjectId("5d0d1deafa80e3002820af05")}}, 
                                    {'$unwind':"$data"}]):
    aw.append(documents)
# for documents in c_ucl.find({"user":ObjectId("5d0d1deafa80e3002820af05")}): 
#     aw.append(documents)

dic_flattened = [flatten(d) for d in aw]
df_main = pd.DataFrame(dic_flattened)
df_main

Querying Collectables Logs Table

,__v,_id,data__id,data_action_item_id,data_action_item_type,data_catalogue_id,data_created_at,data_quantity,data_reason_type,type,user
0,0,5d0d2028fa80e30028215807,5d0d2028fa80e30028215808,NaN,NaN,1,2019-06-21 18:21:28.845,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
1,0,5d0d2028fa80e30028215807,5d0d209dfa80e30028217374,NaN,NaN,1,2019-06-21 18:23:25.023,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
2,0,5d0d2028fa80e30028215807,5d0d278e8185c200191e845f,NaN,NaN,1,2019-06-21 18:53:02.011,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
3,0,5d0d2028fa80e30028215807,5d0d2a25fa80e3002822abc9,NaN,NaN,1,2019-06-21 19:04:05.005,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
4,0,5d0d2028fa80e30028215807,5d0d3197fa80e30028235a25,NaN,NaN,1,2019-06-21 19:35:51.293,-1,END_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
5,0,5d0d2028fa80e30028215807,5d0d31a08185c200191f510e,NaN,NaN,1,2019-06-21 19:36:00.567,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
6,0,5d0d2028fa80e30028215807,5d0d31aefa80e30028236606,NaN,NaN,1,2019-06-21 19:36:14.543,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
7,0,5d0d2028fa80e30028215807,5d0d31ba8185c200191f51df,NaN,NaN,1,2019-06-21 19:36:26.086,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
8,0,5d0d2028fa80e30028215807,5d0d31d4fa80e30028237106,NaN,NaN,1,2019-06-21 19:36:52.778,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
9,0,5d0d2028fa80e30028215807,5d0d31e6fa80e30028237175,NaN,NaN,1,2019-06-21 19:37:10.108,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
10,0,5d0d2028fa80e30028215807,5d0d31f48185c200191f5ba2,NaN,NaN,1,2019-06-21 19:37:24.892,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
11,0,5d0d2028fa80e30028215807,5d0d32078185c200191f5c46,NaN,NaN,1,2019-06-21 19:37:43.609,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
12,0,5d0d2028fa80e30028215807,5d0d321bfa80e3002823723c,NaN,NaN,1,2019-06-21 19:38:03.768,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
13,0,5d0d2028fa80e30028215807,5d0d32278185c200191f661a,NaN,NaN,1,2019-06-21 19:38:15.389,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
14,0,5d0d2028fa80e30028215807,5d0d4325fa80e3002825da2c,NaN,NaN,1,2019-06-21 20:50:45.684,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
15,0,5d0d2028fa80e30028215807,5d0e3104fa80e300284ca3b5,NaN,NaN,1,2019-06-22 13:45:40.266,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
16,0,5d0d2028fa80e30028215807,5d0e95e48185c200195d074b,5d0e95af8185c200195d067c,Mail,1,2019-06-22 20:56:04.783,1,CLAIMED_FROM_MAIL,HARD_CURRENCY,5d0d1deafa80e3002820af05
17,0,5d0d2028fa80e30028215807,5d0e95edfa80e30028628c77,5d0e95af8185c200195d067b,Mail,1,2019-06-22 20:56:13.064,2,CLAIMED_FROM_MAIL,HARD_CURRENCY,5d0d1deafa80e3002820af05
18,0,5d0d2028fa80e30028215807,5d0ea4b48185c200195e80af,NaN,NaN,1,2019-06-22 21:59:16.497,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
19,0,5d0d2028fa80e30028215807,5d0ea76e8185c200195e9e4c,NaN,NaN,1,2019-06-22 22:10:54.146,-5,DAILY_KIT_REFRESH,HARD_CURRENCY,5d0d1deafa80e3002820af05
20,0,5d0d2028fa80e30028215807,5d0eb9a58185c200195f150a,NaN,NaN,1,2019-06-22 23:28:37.885,-7,SPEEDUP_USE,HARD_CURRENCY,5d0d1deafa80e3002820af05
21,0,5d0d2028fa80e30028215807,5d0eb9ab8185c200195f1521,NaN,NaN,1,2019-06-22 23:28:43.291,-3,SPEEDUP_USE,HARD_CURRENCY,5d0d1deafa80e3002820af05
22,0,5d0d2028fa80e30028215807,5d0f477a8185c200197cddbb,NaN,NaN,1,2019-06-23 09:33:46.156,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
23,0,5d0d2028fa80e30028215807,5d0fd4a28185c20019961d34,5d0fd4918185c20019961d1e,Mail,1,2019-06-23 19:36:02.164,1,CLAIMED_FROM_MAIL,HARD_CURRENCY,5d0d1deafa80e3002820af05
24,0,5d0d2028fa80e30028215807,5d0fd4a78185c20019961fac,5d0fd4918185c20019961d1d,Mail,1,2019-06-23 19:36:07.933,7,CLAIMED_FROM_MAIL,HARD_CURRENCY,5d0d1deafa80e3002820af05
25,0,5d0d2028fa80e30028215807,5d0fd829fa80e300289ba1ff,NaN,NaN,1,2019-06-23 19:51:05.262,-48,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
26,0,5d0d2028fa80e30028215807,5d0fd90ffa80e300289bdcf7,NaN,NaN,1,2019-06-23 19:54:55.809,-10,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
27,0,5d0d2028fa80e30028215807,5d0fd9328185c20019970429,NaN,NaN,1,2019-06-23 19:55:30.915,-5,END_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
28,0,5d0d2028fa80e30028215807,5d0fe376fa80e300289e9a90,NaN,NaN,1,2019-06-23 20:39:18.684,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
29,0,5d0d2028fa80e30028215807,5d0fe91bfa80e300289f0a6c,NaN,NaN,1,2019-06-23 21:03:23.696,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
...,...,...,...,...,...,...,...,...,...,...,...
369,0,5d0d2028fa80e30028215807,5d121a2451a95c001996d46b,NaN,NaN,1,2019-06-25 12:57:08.947,-1,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
370,0,5d0d2028fa80e30028215807,5d121a2bfe662b0012b03d4d,NaN,NaN,1,2019-06-25 12:57:15.372,-2,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
371,0,5d0d2028fa80e30028215807,5d121a3f51a95c001996d831,NaN,NaN,1,2019-06-25 12:57:35.943,-5,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
372,0,5d0d2028fa80e30028215807,5d121a57fe662b0012b063ea,NaN,NaN,1,2019-06-25 12:57:59.935,-10,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
373,0,5d0d2028fa80e30028215807,5d121a69fe662b0012b069a4,NaN,NaN,1,2019-06-25 12:58:17.485,-20,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
374,0,5d0d2028fa80e30028215807,5d121b91723536001859992e,NaN,NaN,1,2019-06-25 13:03:13.831,-30,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
375,0,5d0d2028fa80e30028215807,5d121d32c5ebf800117ca426,NaN,NaN,1,2019-06-25 13:10:10.885,-61,QUICK_TRAINING,HARD_CURRENCY,5d0d1deafa80e3002820af05
376,0,5d0d2028fa80e30028215807,5d121d5972353600185a4a7f,NaN,NaN,1,2019-06-25 13:10:49.776,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05
377,0,5d0d2028fa80e30028215807,5d126b19c5ebf800118d7126,5d126a3b72353600186a724b,Mail,1,2019-06-25 18:42:33.321,3,CLAIMED_FROM_MAIL,HARD_CURRENCY,5d0d1deafa80e3002820af05
378,0,5d0d2028fa80e30028215807,5d126b3172353600186ad8fa,NaN,NaN,1,2019-06-25 18:42:57.809,-2,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
379,0,5d0d2028fa80e30028215807,5d126b3572353600186add31,NaN,NaN,1,2019-06-25 18:43:01.032,-10,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
380,0,5d0d2028fa80e30028215807,5d126b38c5ebf800118d7f03,NaN,NaN,1,2019-06-25 18:43:04.244,-3,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
381,0,5d0d2028fa80e30028215807,5d126b40c5ebf800118d836a,NaN,NaN,1,2019-06-25 18:43:12.901,-5,DAILY_KIT_REFRESH,HARD_CURRENCY,5d0d1deafa80e3002820af05
382,0,5d0d2028fa80e30028215807,5d126b48c5ebf800118d86e5,NaN,NaN,1,2019-06-25 18:43:20.111,-10,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
383,0,5d0d2028fa80e30028215807,5d126b54c5ebf800118d8ec5,NaN,NaN,1,2019-06-25 18:43:32.026,-15,DAILY_KIT_REFRESH,HARD_CURRENCY,5d0d1deafa80e3002820af05
384,0,5d0d2028fa80e30028215807,5d126b5bc5ebf800118d9050,NaN,NaN,1,2019-06-25 18:43:39.132,-72,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
385,0,5d0d2028fa80e30028215807,5d126b5ec5ebf800118d9482,NaN,NaN,1,2019-06-25 18:43:42.292,-1,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
386,0,5d0d2028fa80e30028215807,5d1270cd72353600186c9802,NaN,NaN,1,2019-06-25 19:06:53.739,-10,ENERGY_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
387,0,5d0d2028fa80e30028215807,5d1270d4c5ebf800118f84f8,NaN,NaN,1,2019-06-25 19:07:00.541,-20,ENERGY_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
388,0,5d0d2028fa80e30028215807,5d1270d9c5ebf800118f867f,NaN,NaN,1,2019-06-25 19:07:05.780,-30,ENERGY_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
389,0,5d0d2028fa80e30028215807,5d1270e0c5ebf800118f8807,NaN,NaN,1,2019-06-25 19:07:12.415,-50,ENERGY_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
390,0,5d0d2028fa80e30028215807,5d1270e6c5ebf800118f8990,NaN,NaN,1,2019-06-25 19:07:18.909,-75,ENERGY_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
391,0,5d0d2028fa80e30028215807,5d12828bc5ebf8001192bccf,885b1d05-ad3f-4066-a0eb-905dd0808ef5,TrailPayOrderId,1,2019-06-25 20:22:35.429,80,TAPJOY_BILLING,HARD_CURRENCY,5d0d1deafa80e3002820af05
392,0,5d0d2028fa80e30028215807,5d12fd9ac5ebf80011a4a99b,ff12bcdb-38b6-4a38-8772-1bf092a1ea49,TrailPayOrderId,1,2019-06-26 05:07:38.375,1,TAPJOY_BILLING,HARD_CURRENCY,5d0d1deafa80e3002820af05
393,0,5d0d2028fa80e30028215807,5d12ff12c5ebf80011a4e7c9,NaN,NaN,1,2019-06-26 05:13:54.361,-36,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
394,0,5d0d2028fa80e30028215807,5d12ff17c5ebf80011a4eac8,NaN,NaN,1,2019-06-26 05:13:59.789,-50,DAILY_KIT_REFRESH,HARD_CURRENCY,5d0d1deafa80e3002820af05
395,0,5d0d2028fa80e30028215807,5d12ff1ec5ebf80011a4ec5f,NaN,NaN,1,2019-06-26 05:14:06.963,-24,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
396,0,5d0d2028fa80e30028215807,5d12ff227235360018847dd1,NaN,NaN,1,2019-06-26 05:14:10.200,-10,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
397,0,5d0d2028fa80e30028215807,5d12ff257235360018848170,NaN,NaN,1,2019-06-26 05:14:13.341,-5,DAILY_KIT_REWARDS,HARD_CURRENCY,5d0d1deafa80e3002820af05
398,0,5d0d2028fa80e30028215807,5d133762114e23001a7fa451,NaN,NaN,1,2019-06-26 09:14:10.925,5,LEVEL_UP,HARD_CURRENCY,5d0d1deafa80e3002820af05

In [32]:
df_main.groupby('data_reason_type').agg({'data_quantity':'sum'})

                   data_quantity
data_reason_type
CLAIMED_FROM_MAIL             21
DAILY_KIT_REFRESH           -215
DAILY_KIT_REWARDS           -668
END_TRAINING                 -60
ENERGY_PURCHASE             -370
KIT_KEYS_PURCHASE         -25650
LEVEL_UP                     125
QUICK_TRAINING             -1067
SPEEDUP_USE                  -10
TAPJOY_BILLING               163

In [36]:
aw = []
c_users = cursor.superstars.users
for documents in c_users.find({"_id":ObjectId("5d0d1deafa80e3002820af05")}): 
    aw.append(documents)


dic_flattened = [flatten(d) for d in aw]
users = pd.DataFrame(dic_flattened)
aw

[{'_id': ObjectId('5d0d1deafa80e3002820af05'),
  'collectables': {'player_items': {'upgrades': {'training_cards': [{'quantity': 3,
       '_id': ObjectId('5d133a79114e23001a80088e'),
       'id': 2},
      {'quantity': 3, '_id': ObjectId('5d133a79114e23001a80088d'), 'id': 3},
      {'quantity': 26, '_id': ObjectId('5d133a627119e600139c838b'), 'id': 4},
      {'quantity': 1, '_id': ObjectId('5d133a79114e23001a80088c'), 'id': 45},
      {'quantity': 1, '_id': ObjectId('5d133a79114e23001a80088b'), 'id': 46}],
     'training_speedup_cards': [{'quantity': 0,
       '_id': ObjectId('5d12ff12c5ebf80011a4e957'),
       'id': 1},
      {'quantity': 1, '_id': ObjectId('5d12ff12c5ebf80011a4e956'), 'id': 2},
      {'quantity': 1, '_id': ObjectId('5d12ff12c5ebf80011a4e955'), 'id': 3},
      {'quantity': 173, '_id': ObjectId('5d12ff12c5ebf80011a4e954'), 'id': 4},
      {'quantity': 17, '_id': ObjectId('5d126ff972353600186c7f80'), 'id': 5}],
     'passive_tokens': [],
     'active_tokens': [],
     'choke_cards': []}},
   'hard_currency': [{'_id': ObjectId('5d0d1deafa80e3002820af06'),
     'id': 1,
     'quantity': 952681}],
   'soft_currency': [{'_id': ObjectId('5d0d1deafa80e3002820af08'),
     'id': 1,
     'quantity': 15070},
    {'_id': ObjectId('5d0d1deafa80e3002820af07'), 'id': 2, 'quantity': 841000},
    {'_id': ObjectId('5d0e31f5fa80e300284cb43b'), 'id': 3, 'quantity': 70},
    {'_id': ObjectId('5d0e95e48185c200195d075d'), 'id': 4, 'quantity': 11}],
   'player_fragments': [{'quantity': 967,
     '_id': ObjectId('5d126bd3c5ebf800118da334'),
     'id': -1},
    {'quantity': 236, '_id': ObjectId('5d126bd3c5ebf800118da333'), 'id': -2},
    {'quantity': 29, '_id': ObjectId('5d126bd3c5ebf800118da094'), 'id': -3}],
   'rename_tokens': [{'quantity': 2,
     '_id': ObjectId('5d0d1deafa80e3002820af0a'),
     'id': 1}],
   'training_cards': [],
   'choke_cards': [],
   'kit_keys': [{'quantity': 1,
     '_id': ObjectId('5d126bc772353600186b3d7e'),
     'id': 'BASIC_SPONSOR'},
    {'quantity': 0,
     '_id': ObjectId('5d12ff1fc5ebf80011a4edee'),
     'id': 'ELITE_SPONSOR'},
    {'quantity': 0,
     '_id': ObjectId('5d12ff1fc5ebf80011a4eded'),
     'id': 'PURCHASED_BASIC_SPONSOR'},
    {'quantity': 0,
     '_id': ObjectId('5d12ff1fc5ebf80011a4edec'),
     'id': 'PURCHASED_ELITE_SPONSOR'}],
   'training_speedup_cards': []},
  'login_details': {'tutorial_step': 1,
   'last_request_at': datetime.datetime(2019, 6, 26, 9, 27, 26, 28000),
   'last_used_version': 23},
  'sign_up_details': {'device': {'id': '0e57846da0c66c1507f94c49ac526b58',
    'model': 'HUAWEI DUA-L22',
    'height': 1440,
    'width': 720,
    'os_version': 'Android OS 8.1.0 / API-27 (HONORDUA-L22/1.0.0.151(C432))'},
   'app': {'platform': 'UNITY_Android', 'version': '22'},
   'campaign_source': 'utm_source=google-play&utm_medium=organic',
   'method': 'GUEST'},
  'training_center_slot': {'status': 0},
  'tasks': {'daily': {'data': [{'current_progress': 2,
      'claimed': 0,
      '_id': ObjectId('5d12fcca723536001883df1f'),
      'id': -10},
     {'current_progress': 2,
      'claimed': 0,
      '_id': ObjectId('5d12fcca723536001883df20'),
      'id': 1},
     {'current_progress': 1,
      'claimed': 1,
      '_id': ObjectId('5d12fcca723536001883df21'),
      'id': 2},
     {'current_progress': 0,
      'claimed': 0,
      '_id': ObjectId('5d12fcca723536001883df22'),
      'id': 3},
     {'current_progress': 64,
      'claimed': 1,
      '_id': ObjectId('5d12fcca723536001883df23'),
      'id': 5}],
    'date': datetime.datetime(2019, 6, 26, 0, 0)}},
  'daily_deals': {'purchased': 3,
   'slots': [{'rewards': [{'id': 3, 'type': 'TrainingCard', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec5c'),
     'id': 1,
     'has_purchased': True,
     'currency_needed': 0},
    {'rewards': [{'id': 2, 'type': 'TrainingSpeedupCard', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec5b'),
     'id': 2,
     'has_purchased': False,
     'currency_needed': 10000},
    {'rewards': [{'id': 46, 'type': 'TrainingCard', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec5a'),
     'id': 3,
     'has_purchased': True,
     'currency_needed': 10},
    {'rewards': [{'id': 'BASIC_SPONSOR', 'type': 'KitKey', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec59'),
     'id': 4,
     'has_purchased': True,
     'currency_needed': 24},
    {'rewards': [{'id': 45, 'type': 'TrainingCard', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec58'),
     'id': 5,
     'has_purchased': True,
     'currency_needed': 5},
    {'rewards': [{'id': 2, 'type': 'SoftCurrency', 'quantity': 50000}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec57'),
     'id': 6,
     'has_purchased': False,
     'currency_needed': 50},
    {'rewards': [{'id': 'BASIC_SPONSOR', 'type': 'KitKey', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec56'),
     'id': 7,
     'has_purchased': False,
     'currency_needed': 90},
    {'rewards': [{'id': -2, 'type': 'PlayerFragment', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec55'),
     'id': 8,
     'has_purchased': False,
     'currency_needed': 1},
    {'rewards': [{'id': 1, 'type': 'RenameToken', 'quantity': 1}],
     '_id': ObjectId('5d12ff17c5ebf80011a4ec54'),
     'id': 9,
     'has_purchased': False,
     'currency_needed': 13}],
   'last_refreshed_at': datetime.datetime(2019, 6, 25, 18, 38, 49, 845000)},
  'status': 1,
  'firebase_uid': 'pEZ2uqT31dfZ1ARjAvbZWd9gRcJ3',
  'name_change_count': 1,
  'name': 'Martin Ellis',
  'email': 'hw+1561140714724@hws.com',
  'app_data': [{'_id': ObjectId('5d0d1debfa80e3002820af1d'),
    'app_type': 'UNITY_Android',
    'last_used_version': 23,
    'app_kind': '1',
    'last_requested_at': datetime.datetime(2019, 6, 26, 9, 27, 26, 27000)}],
  'dashboard_dots': [{'_id': ObjectId('5d0d1e4b8185c200191d2ee7'),
    'id': 1,
    'status': 0},
   {'_id': ObjectId('5d0d1e4b8185c200191d2ee6'), 'id': 2, 'status': 0},
   {'_id': ObjectId('5d0d1e4b8185c200191d2ee5'), 'id': 3, 'status': 0},
   {'_id': ObjectId('5d0d1e4b8185c200191d2ee4'), 'id': 4, 'status': 0},
   {'_id': ObjectId('5d0d1e4b8185c200191d2ee3'), 'id': 5, 'status': 0},
   {'_id': ObjectId('5d0d1e4b8185c200191d2ee2'), 'id': 6, 'status': 1}],
  'training_centers': [{'_id': ObjectId('5d0d1debfa80e3002820af1e'),
    'id': 1,
    'type': 'NORMAL',
    'expires_at': datetime.datetime(2119, 6, 21, 18, 11, 55, 415000)}],
  'salt': '9b81d1a14d509937af118bf28874bb2c',
  'hash': '5559a227a796d7d85190c4e67530a594a45b71b1fb4a4fd9eba1d75ee3745bce4870de67a66104bdf896505f2ad9f54f70ec9cb70797ab0780c50b5ac68689dc',
  'created_at': datetime.datetime(2019, 6, 21, 18, 11, 54, 731000),
  'updatedAt': datetime.datetime(2019, 6, 26, 9, 27, 26, 30000),
  '__v': 2132,
  'short_id': 'G1FMT7HW6'}]

In [9]:
temp = df_main[df_main['user']=='5d0d1deafa80e3002820af05']
temp

Empty DataFrame
Columns: [__v, _id, data__id, data_action_item_id, data_action_item_type, data_catalogue_id, data_created_at, data_quantity, data_reason_type, type, user]
Index: []

In [7]:
df = df_main[~df_main['user'].isin(tgpl_users['_id'])]

print('Data Wrangling')
hitcoins = df[df['data_catalogue_id']== '1']

hitcoins = hitcoins[ hitcoins['data_quantity'] < 0 ]
hitcoins['data_quantity'] = -hitcoins['data_quantity']

_ = hitcoins.groupby(['data_reason_type','user']).agg({'data_quantity':'sum'}).reset_index()
_

Data Wrangling

      data_reason_type                      user  data_quantity
0    DAILY_KIT_REFRESH  5c97b32e9732f62d3e3adb36             20
1    DAILY_KIT_REFRESH  5cbe8f7b2bdfca07d876db65              5
2    DAILY_KIT_REFRESH  5cd802e6822ea36f394009c2              5
3    DAILY_KIT_REFRESH  5cf1312767847c1b7cf3b1af              5
4    DAILY_KIT_REFRESH  5cf67555f588234bca10205d              5
5    DAILY_KIT_REFRESH  5d03be72ad6fe1001851653c              5
6    DAILY_KIT_REFRESH  5d06a9b7a6264f03597bcbac              5
7    DAILY_KIT_REFRESH  5d07107cc61219034a416293              5
8    DAILY_KIT_REFRESH  5d07c55fa6264f0359a380da              5
9    DAILY_KIT_REFRESH  5d0d1deafa80e3002820af05             70
10   DAILY_KIT_REFRESH  5d0f17d38185c20019710bd7              5
11   DAILY_KIT_REFRESH  5d10496c8185c20019a6267f              5
12   DAILY_KIT_REFRESH  5d11b8168185c20019e05992              5
13   DAILY_KIT_REFRESH  5d11ca1c8185c20019e2a246              5
14   DAILY_KIT_REFRESH  5d11f5e351a95c00198e0bae              5
15   DAILY_KIT_REFRESH  5d11f69f51a95c00198e1f47              5
16   DAILY_KIT_REFRESH  5d11f9bbfe662b0012a78466              5
17   DAILY_KIT_REFRESH  5d123a07c5ebf80011829e3d              5
18   DAILY_KIT_REFRESH  5d125e06723536001867c7e2              5
19   DAILY_KIT_REWARDS  5c97b32e9732f62d3e3adb36             32
20   DAILY_KIT_REWARDS  5c9f50ebcce14050efc31673            168
21   DAILY_KIT_REWARDS  5ca9c4c38a3b1c4e26b8e44f             20
22   DAILY_KIT_REWARDS  5caed11be7c7b00ea78f9307              1
23   DAILY_KIT_REWARDS  5cc5a16b3bd08a27a8fb6ea7              8
24   DAILY_KIT_REWARDS  5ccabd465774092ae0eda0aa             32
25   DAILY_KIT_REWARDS  5cd6cbef4e76e01041fd0272             10
26   DAILY_KIT_REWARDS  5cd7f4da112ed13abd48d5fc              4
27   DAILY_KIT_REWARDS  5cd802e6822ea36f394009c2              2
28   DAILY_KIT_REWARDS  5cd87e71822ea36f3944c746              2
29   DAILY_KIT_REWARDS  5cd989994e4f6d53213ab7f5             42
..                 ...                       ...            ...
204        SPEEDUP_USE  5d0fb5b68185c20019900d49             35
205        SPEEDUP_USE  5d1123a0fa80e30028d53059             14
206        SPEEDUP_USE  5d11ca1c8185c20019e2a246             11
207       TC2_PURCHASE  5c9eedf0cda26a6a0c2dd1a5             30
208       TC2_PURCHASE  5ca74d8074aaef18f702fb89             30
209       TC2_PURCHASE  5ca9c4c38a3b1c4e26b8e44f             30
210       TC2_PURCHASE  5cb4834739c35e779e3b87cd             30
211       TC2_PURCHASE  5cc148ed70a5367bb8c7a3dc             30
212       TC2_PURCHASE  5cc5f1d6277edc24da8982ae             30
213       TC2_PURCHASE  5cd78c54cfd59d105c9c409a             30
214       TC2_PURCHASE  5cd8f1f562ebdd106387386e             30
215       TC2_PURCHASE  5d0c15f2332aa70015724d1c             30
216       TC2_PURCHASE  5d0e16f0fa80e3002848c07c             30
217       TC2_PURCHASE  5d107ea8fa80e30028b62951             30
218       TC2_PURCHASE  5d1088938185c20019aefa3b             30
219       TC2_PURCHASE  5d10a00c8185c20019b3fb2d             30
220       TC2_PURCHASE  5d1125cefa80e30028d56a2a             30
221       TC2_PURCHASE  5d1193938185c20019dab9d5             30
222       TC2_PURCHASE  5d119a00fa80e30028e55e01             30
223       TC2_PURCHASE  5d11adabfa80e30028e891fb             30
224       TC2_PURCHASE  5d11b8168185c20019e05992             30
225       TC2_PURCHASE  5d11ba1dfa80e30028ea1ae4             30
226       TC2_PURCHASE  5d11c262fa80e30028eafc9a             30
227       TC2_PURCHASE  5d11cb7cfe662b00129de39d             30
228       TC2_PURCHASE  5d11e1bf51a95c00198b6e1e             30
229       TC2_PURCHASE  5d11e93551a95c00198c25a5             30
230       TC2_PURCHASE  5d1204b751a95c00198ff566             30
231       TC2_PURCHASE  5d1225e0c5ebf800117e564d             30
232       TC2_PURCHASE  5d123a9c723536001860450f             30
233       TC2_PURCHASE  5d1240c0c5ebf800118430fa             30

[234 rows x 3 columns]

In [ ]:
_ = _[_['data']]

In [18]:
c_payment_orders = cursor.superstars.payment_orders

aw = []
for documents in c_payment_orders.find({"updated_at" : {"$gte" : start, "$lte" : end}}  ):
    aw.append(documents)
dic_flattened = [flatten(d) for d in aw]
purchased = pd.DataFrame(dic_flattened)
purchased

,__v,_id,created_at,currency_code,details_gateway,details_order_id,details_returned_params,items_0__id,items_0_id,items_0_type,revenue_bottom_line,revenue_top_line,status,type,updated_at,user_email,user_id,user_name
0,0,5d0a9d313c8b7e0018d40161,2019-06-19 20:38:09.131,INR,google_in_app_billing,GPA.3359-5045-6146-82064,"{""receipt"":""{\""Store\"":\""GooglePlay\"",\""Transa...",5d0a9d313c8b7e0018d40162,6,HARD_CURRENCY_PACKAGE,5530,7900,2,GENERAL_PURCHASE,2019-06-19 20:38:10.361,hw+1560975497461@hws.com,5d0a9889d0dff00011543f46,Flintstone

In [ ]:
df = df_main[~df_main['user'].isin(tgpl_users['_id'])]

print('Data Wrangling')
hitcoins = df[df['data_catalogue_id']== '1']

hitcoins = hitcoins[ hitcoins['data_quantity'] < 0 ]
hitcoins['data_quantity'] = -hitcoins['data_quantity']

_ = hitcoins.groupby(['data_reason_type','user']).agg({'data_quantity':'sum'}).reset_index()
_ = _.groupby(['data_reason_type']).agg({'data_quantity':'max'}).reset_index()

hitcoins = hitcoins.groupby(['data_reason_type']).agg({'data_quantity':'sum','user':pd.Series.nunique}).reset_index()
hitcoins['Hitcoins Spent per User'] = (hitcoins['data_quantity'] / hitcoins['user']).round(1)

hitcoins = pd.merge(hitcoins,_,on='data_reason_type',how='inner')
hitcoins.columns = ['Feature','Total HC Spent','Unique Users','HC Spent per Unique User','Max HC Spent']
hitcoins['Feature'] = hitcoins['Feature'].replace({"DAILY_KIT_REFRESH" : "Daily Deals Refresh",
                                                     "DAILY_KIT_REWARDS" : "Daily Deals Purchase",
                                                     "END_TRAINING" : "Finish Training",
                                                     "ENERGY_PURCHASE" : "Energy Purchase",
                                                     "KIT_KEYS_PURCHASE" : "Sponsor Box Open",
                                                     "QUICK_TRAINING" : "Instant Training",
                                                     "SPEEDUP_USE" : "Speedup Purchase"})

custom_dict = {"Instant Training":0,"Finish Training":1,"Sponsor Box Open":2,"Speedup Purchase":3,
               "Daily Deals Purchase":4,"Daily Deals Refresh":5,"Energy Purchase":6}
hitcoins = hitcoins.iloc[hitcoins['Feature'].map(custom_dict).argsort()]
ss_total = hitcoins['Total HC Spent'].sum()

hitcoins['Total HC Spent'] = hitcoins.apply(lambda x: "{:,}".format(x['Total HC Spent']), axis=1)
hitcoins['Unique Users'] = hitcoins.apply(lambda x: "{:,}".format(x['Unique Users']), axis=1)
hitcoins['HC Spent per Unique User'] = hitcoins.apply(lambda x: "{:,}".format(x['HC Spent per Unique User']), axis=1)
hitcoins['Max HC Spent'] = hitcoins.apply(lambda x: "{:,}".format(x['Max HC Spent']), axis=1)
ss_hitcoins = hitcoins
    
    try:
        df = df_main[df_main['user'].isin(tgpl_users['_id'])]

        hitcoins = df[df['data_catalogue_id']== '1']

        hitcoins = hitcoins[ hitcoins['data_quantity'] < 0 ]
        hitcoins['data_quantity'] = -hitcoins['data_quantity']

        _ = hitcoins.groupby(['data_reason_type','user']).agg({'data_quantity':'sum'}).reset_index()
        _ = _.groupby(['data_reason_type']).agg({'data_quantity':'max'}).reset_index()

        hitcoins = hitcoins.groupby(['data_reason_type']).agg({'data_quantity':'sum','user':pd.Series.nunique}).reset_index()
        hitcoins['Hitcoins Spent per User'] = (hitcoins['data_quantity'] / hitcoins['user']).round(1)

        hitcoins = pd.merge(hitcoins,_,on='data_reason_type',how='inner')
        hitcoins.columns = ['Feature','Total HC Spent','Unique Users','HC Spent per Unique User','Max HC Spent']
        hitcoins['Feature'] = hitcoins['Feature'].replace({"DAILY_KIT_REFRESH" : "Daily Deals Refresh",
                                                             "DAILY_KIT_REWARDS" : "Daily Deals Purchase",
                                                             "END_TRAINING" : "Finish Training",
                                                             "ENERGY_PURCHASE" : "Energy Purchase",
                                                             "KIT_KEYS_PURCHASE" : "Sponsor Box Open",
                                                             "QUICK_TRAINING" : "Instant Training",
                                                             "SPEEDUP_USE" : "Speedup Purchase"})

        custom_dict = {"Instant Training":0,"Finish Training":1,"Sponsor Box Open":2,"Speedup Purchase":3,
                       "Daily Deals Purchase":4,"Daily Deals Refresh":5,"Energy Purchase":6}
        hitcoins = hitcoins.iloc[hitcoins['Feature'].map(custom_dict).argsort()]
        tgpl_total = hitcoins['Total HC Spent'].sum()


        hitcoins['Total HC Spent'] = hitcoins.apply(lambda x: "{:,}".format(x['Total HC Spent']), axis=1)
        hitcoins['Unique Users'] = hitcoins.apply(lambda x: "{:,}".format(x['Unique Users']), axis=1)
        hitcoins['HC Spent per Unique User'] = hitcoins.apply(lambda x: "{:,}".format(x['HC Spent per Unique User']), axis=1)
        hitcoins['Max HC Spent'] = hitcoins.apply(lambda x: "{:,}".format(x['Max HC Spent']), axis=1)
        tgpl_hitcoins = hitcoins
    except:
        data = [["Daily Deals Refresh",0,0,0,0],
                ["Daily Deals Purchase",0,0,0,0],
                ["Finish Training",0,0,0,0],
                ["Energy Purchase",0,0,0,0],
                ["Sponsor Box Open",0,0,0,0],
                ["Instant Training",0,0,0,0],
                ["Speedup Purchase",0,0,0,0]] 
        tgpl_hitcoins= pd.DataFrame(data, columns = ['Feature','Total HC Spent','Unique Users','HC Spent per Unique User','Max HC Spent']) 
        tgpl_hitcoins
    print('Getting Purchase Details')
    
    cursor = pymongo.MongoClient("mongodb://" + os.environ['user'] + ':' + 
                                 os.environ['pass'] + '@' + os.environ['db1']  + "/?authSource=" + 
                                 os.environ['dbname']) 
    c_payment_orders = cursor.superstars.payment_orders
    
    aw = []
    for documents in c_payment_orders.find({"updated_at" : {"$gte" : start, "$lte" : end}}  ):
        aw.append(documents)
    dic_flattened = [flatten(d) for d in aw]
    purchased = pd.DataFrame(dic_flattened)
    
    try:
            purchased = purchased[purchased['status']==2]
            purchased = purchased[purchased['currency_code']!="TGPL"]
            purchased = purchased[['items_0_id','items_0_id']]
            purchased.columns = ['id','type']

            data = [[1,50,49], [2,250,199], [3,700,499], [4,2500,1599], [5,6500,3999], [6,14000,7900]] 
            rates = pd.DataFrame(data, columns = ['id', 'hitcoins', 'rates']) 
            rates['hitcoins'] = rates.apply(lambda x: "{:,}".format(x['hitcoins']), axis=1)

            purchased = pd.merge (purchased,rates,on='id',how='inner')
            purchased = purchased['hitcoins'].astype(int).sum()
    except:
            purchased = 0
    ss_purchased=purchased
    
    aw = []
    for documents in c_payment_orders.find({"updated_at" : {"$gte" : start, "$lte" : end}}  ):
        aw.append(documents)
    dic_flattened = [flatten(d) for d in aw]
    purchased = pd.DataFrame(dic_flattened)

    try:
            purchased = purchased[purchased['status']==2]
            purchased = purchased[purchased['currency_code']=='TGPL']
            purchased = purchased[['items_0_id','items_0_id']]
            purchased.columns = ['id','type']

            data = [[1,50,49], [2,250,199], [3,700,499], [4,2500,1599], [5,6500,3999], [6,14000,7900]] 
            rates = pd.DataFrame(data, columns = ['id', 'hitcoins', 'rates']) 
            rates['hitcoins'] = rates.apply(lambda x: "{:,}".format(x['hitcoins']), axis=1)

            purchased = pd.merge (purchased,rates,on='id',how='inner')
            purchased = purchased['hitcoins'].astype(int).sum()
    except:
            purchased = 0
    tgpl_purchased=purchased

    numeric_col_mask = ss_hitcoins.dtypes.apply(lambda d: issubclass(np.dtype(d).type, np.number))
    
    # Dict used to center the table headers
    d = dict(selector="col_heading",
        props=[('text-align', 'center'),('font-weight', 'bold'),('font-size', '14px')])
    
    print('Styling')
    style1 = ss_hitcoins.style.set_properties(subset=ss_hitcoins.columns[numeric_col_mask],**{'width':'10em', 'text-align':'right'})\
            .set_properties(subset=ss_hitcoins.columns[~numeric_col_mask],**{'width':'10em', 'text-align':'left'})\
            .set_table_styles([d]).render()
    
    
    numeric_col_mask = tgpl_hitcoins.dtypes.apply(lambda d: issubclass(np.dtype(d).type, np.number))
    
    d = dict(selector="col_heading",
        props=[('text-align', 'center'),('font-weight', 'bold'),('font-size', '14px')])
    
    style2 = tgpl_hitcoins.style.set_properties(subset=tgpl_hitcoins.columns[numeric_col_mask],**{'width':'10em', 'text-align':'right'})\
            .set_properties(subset=tgpl_hitcoins.columns[~numeric_col_mask],**{'width':'10em', 'text-align':'left'})\
            .set_table_styles([d]).render()
    print('Preparing Mail Content')
    html_str = """<html>
    <head>
    <style>
    
        h2 {
            font-family: Helvetica, Arial, sans-serif;
        }
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 5px;
            font-family: Helvetica, Arial, sans-serif;
            font-size: 100%;
        }
        tbody tr:nth-child(odd) {background: #eee}
        tbody tr:nth-child(even) {background: #fff}
        table tbody tr td:hover {
            background-color: #fcffb2;
        }
        .row_heading, .blank{
            display: none;
        }
        .col_heading{
            background-color: #CCD1D1;
        }
        .row1, .row3, .row5{
            background-color: #EAEDED;
        }
        .row0:hover, .row2:hover, .row4:hover, .row6:hover{
            background-color: #fcffb2;
        }
        .col1, .col2, .col3, .col4, .col5{
            text-align: right;
        }
        .col0, .col1, .col2, .col3, .col4, .col5{
            font-weight: normal;
        }
        .col_heading, .level0, .blank{
            font-weight: bold;
        }
    </style>
    </head>
    <body>
    """
    
    ss_total = "{:,}".format(int(ss_total))
    tgpl_total = "{:,}".format(int(tgpl_total))
    ss_purchased = "{:,}".format(int(ss_purchased))
    tgpl_purchased = "{:,}".format(int(tgpl_purchased))

    html_str += f"""
    <img src="https://d8tuj5f40nouo.cloudfront.net/images/web/landing/logo.png" width="200" height="83">
    <h2> Hitcoins Usage: {datetime.strftime(end,'%A, %b %d')} </h2>
    <h3>Superstars </h3>
    <h4>Total Hitcoins Spent: {ss_total}</h4> 
    <h4>Hitcoins Purchased - {ss_purchased} </h4>
    {style1}
    <br></br>

    <h3>TGPL </h3>
    <h4>Total Hitcoins Spent: {tgpl_total}</h4> 
    <h4>Hitcoins Purchased - {tgpl_purchased} </h4> 
    {style2}
    </body></html>
    
    """
    subject = f"""Hitcoins: {ss_total} ({ss_purchased})  -  TGPL: {tgpl_total} ({tgpl_purchased}) """

    print('Sending Mail')
    gmail_user = os.environ['mail']
    gmail_password = os.environ['mail_token']
    to = ['digest_hitcoins@hitwicket.com','isha@hitwicket.com']
    sent_from = gmail_user
    
    text = "Please use an html reader"
    message = MIMEMultipart(
        "alternative", None, [MIMEText(text), MIMEText(html_str,'html')])
    
    message['From'] = "Analytics <" + os.environ['mail'] + ">"
    message['To'] = ','.join(to)
    message['Subject'] = subject
    
    s = smtplib.SMTP('smtp.gmail.com', 587) 
    s.starttls() 
    s.login(gmail_user, gmail_password) 
    s.sendmail(sent_from, to, message.as_string())  
    s.quit()
    print('Mail Sent')

except:
   from slacker import Slacker
   slack = Slacker(os.environ['accio'])
   if slack.api.test().successful:
       print( f"Connected to {slack.team.info().body['team']['name']}.")
   else:
       print('Try Again!')
   slack.chat.post_message(channel='cron',
                           text="Cron-job for Hitcoins Mailer on " + str(dt.date.today()) + " has failed.", 
                           username='accio')