In [1]:
%load_ext dotenv
%dotenv /home/aurora/.env
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import datetime as dt
from google.cloud import bigquery
import re
import pymongo
import os
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from flatten_json import flatten
from datetime import timedelta, date
import itertools, pandas
#warnings.filterwarnings('ignore')

In [3]:
a = pd.read_excel('./To Shivam C.xlsx')
a

,Unnamed: 0,(Jul'19-Sep'19),(Oct'19-Dec'19),(Jan'20-Mar'20),(Apr'20-Jun'20),(Jul'20-Sep'20),(Oct'20-Dec'20),(Jan'21-Mar'21),(Apr'21-Jun'21),(Jul'21-Sep'21),(Oct'21-Dec'21)
0,Customer Acquisition Assumptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No of Registrations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Android,962500.000,1487500.000,1837500.000,3500000.000,3675000.000,4375000.000,4375000.000,8750000.000,6125000.000,5250000.000
3,iOS,137500.000,212500.000,262500.000,500000.000,525000.000,625000.000,625000.000,1250000.000,875000.000,750000.000
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Active App User Assumptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,D30,0.100,0.110,0.110,0.110,0.110,0.110,0.125,0.125,0.125,0.125
9,D60,0.080,0.090,0.090,0.090,0.090,0.090,0.105,0.105,0.105,0.105
10,D90,0.050,0.060,0.060,0.060,0.060,0.060,0.075,0.075,0.075,0.075
11,D120,0.040,0.050,0.050,0.050,0.050,0.050,0.065,0.065,0.065,0.065
12,D150,0.030,0.040,0.040,0.040,0.040,0.040,0.055,0.055,0.055,0.055
13,D180,0.025,0.035,0.035,0.035,0.035,0.035,0.050,0.050,0.050,0.050
14,D210,0.025,0.035,0.035,0.035,0.035,0.035,0.050,0.050,0.050,0.050
15,D240,0.025,0.035,0.035,0.035,0.035,0.035,0.050,0.050,0.050,0.050
16,D270,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
17,D300,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
18,D330,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
19,D360,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
20,D390,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
21,D420,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
22,D450,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
23,D480,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
24,D510,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
25,D540,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
26,D570,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
27,D600,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
28,D630,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
29,D660,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
30,D690,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
31,D720,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,iOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,D30,0.120,0.130,0.130,0.130,0.130,0.130,0.145,0.145,0.145,0.145
35,D60,0.100,0.110,0.110,0.110,0.110,0.110,0.125,0.125,0.125,0.125
36,D90,0.080,0.090,0.090,0.090,0.090,0.090,0.105,0.105,0.105,0.105
37,D120,0.060,0.070,0.070,0.070,0.070,0.070,0.085,0.085,0.085,0.085
38,D150,0.050,0.060,0.060,0.060,0.060,0.060,0.075,0.075,0.075,0.075
39,D180,0.040,0.050,0.050,0.050,0.050,0.050,0.065,0.065,0.065,0.065
40,D210,0.030,0.040,0.040,0.040,0.040,0.040,0.055,0.055,0.055,0.055
41,D240,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
42,D270,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
43,D300,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
44,D330,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
45,D360,0.020,0.030,0.030,0.030,0.030,0.030,0.045,0.045,0.045,0.045
46,D390,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
47,D420,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
48,D450,0.010,0.020,0.020,0.020,0.020,0.020,0.035,0.035,0.035,0.035
49,D480,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
50,D510,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
51,D540,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
52,D570,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
53,D600,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
54,D630,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
55,D660,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
56,D690,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030
57,D720,0.005,0.015,0.015,0.015,0.015,0.015,0.030,0.030,0.030,0.030

In [4]:
df = a.transpose()
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header
df.head()

Unnamed: 0,Customer Acquisition Assumptions,No of Registrations,Android,iOS,nan,nan,Active App User Assumptions,Android,D30,D60,...,D450,D480,D510,D540,D570,D600,D630,D660,D690,D720
(Jul'19-Sep'19),NaN,NaN,962500,137500,NaN,NaN,NaN,NaN,0.1,0.08,...,0.01,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005
(Oct'19-Dec'19),NaN,NaN,1.4875e+06,212500,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Jan'20-Mar'20),NaN,NaN,1.8375e+06,262500,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Apr'20-Jun'20),NaN,NaN,3.5e+06,500000,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Jul'20-Sep'20),NaN,NaN,3.675e+06,525000,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015

In [8]:
dlist = []
for i in range(24):
    d_previous = (a.iloc[(34+i),1:].tolist())
    d_previous = [item for item in d_previous for j in range(3)]
    dlist.append(d_previous)

In [9]:
df.head()

Unnamed: 0,Customer Acquisition Assumptions,No of Registrations,Android,iOS,nan,nan,Active App User Assumptions,Android,D30,D60,...,D450,D480,D510,D540,D570,D600,D630,D660,D690,D720
(Jul'19-Sep'19),NaN,NaN,962500,137500,NaN,NaN,NaN,NaN,0.1,0.08,...,0.01,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005,0.005
(Oct'19-Dec'19),NaN,NaN,1.4875e+06,212500,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Jan'20-Mar'20),NaN,NaN,1.8375e+06,262500,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Apr'20-Jun'20),NaN,NaN,3.5e+06,500000,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
(Jul'20-Sep'20),NaN,NaN,3.675e+06,525000,NaN,NaN,NaN,NaN,0.11,0.09,...,0.02,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015

In [11]:
df_iOS = df[['iOS']]
df_iOS.columns = ['iOS','nan']
df_iOS.drop('nan',inplace=True,axis =1)
df_iOS

/home/aurora/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

                      iOS
(Jul'19-Sep'19)    137500
(Oct'19-Dec'19)    212500
(Jan'20-Mar'20)    262500
(Apr'20-Jun'20)    500000
(Jul'20-Sep'20)    525000
(Oct'20-Dec'20)    625000
(Jan'21-Mar'21)    625000
(Apr'21-Jun'21)  1.25e+06
(Jul'21-Sep'21)    875000
(Oct'21-Dec'21)    750000

In [12]:
split = df_iOS['iOS'].tolist()
split[:] = [x // 3 for x in split]
split = [item for item in split for i in range(3)]
df_android_month = pd.DataFrame({'iOS':split})

In [13]:
def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)
date_list = []
start_dt = date(19,7,1)
end_dt = date(21,12,31)
for dt in daterange(start_dt, end_dt):
    date_list.append(dt.strftime("%Y-%m"))
    
xy = pd.DataFrame({'months': date_list})
xy.drop_duplicates('months',inplace = True)
xy.reset_index(drop=True, inplace=True)

In [14]:
z = pd.merge(xy, df_android_month , left_index=True,right_index = True)
z.set_index('months',inplace=True)

In [15]:
zero = []
for i in range(24):
    temp = []
    for j in range(i+1):
        temp.append(0)
    zero.append(temp)

In [18]:
anusers = z['iOS'].tolist()
columns = []
for i in range(24):
    temp1 = zero[i] + anusers
    temp1 = temp1[:30]
    columns.append(temp1)

In [19]:
dlist1 = []
for i in range(24):
    temp1 = zero[i] + dlist[i]
    temp1 = temp1[:30]
    dlist1.append(temp1)

In [20]:
c1 = pd.DataFrame((_ for _ in itertools.zip_longest(*columns)), columns=['c1', 'c2', 'c3','c4','c5','c6','c7','c8','c9',
                                                                         'c10','c11','c12','c13','c14','c15','c16','c17',
                                                                         'c18','c19','c20','c21','c22','c23','c24'])
c2 = pd.DataFrame((_ for _ in itertools.zip_longest(*dlist1)), columns=['c1', 'c2', 'c3','c4','c5','c6','c7','c8','c9',
                                                                        'c10','c11','c12','c13','c14','c15','c16','c17',
                                                                        'c18','c19','c20','c21','c22','c23','c24'])

In [21]:
c3 = pd.DataFrame(c1.values*c2.values, columns=c1.columns, index=c1.index)

In [22]:
c4 = c3.sum(axis=1)
c4 = c4.to_frame().reset_index()
c4.columns = ['index','totals']
c4 = c4[['totals']]
c4 = c4.set_index(z.index)

In [25]:
df_iOS_final = pd.merge(z, c4, left_index=True, right_index=True)

In [26]:
df_iOS_final['total_iOS'] = df_iOS_final.sum(axis=1)

In [27]:
df_iOS_final

             iOS      totals   total_iOS
months
19-07    45833.0       0.000   45833.000
19-08    45833.0    5499.960   51332.960
19-09    45833.0   10083.260   55916.260
19-10    70833.0   13749.900   84582.900
19-11    70833.0   20208.210   91041.210
19-12    70833.0   25708.190   96541.190
20-01    87500.0   30249.840  117749.840
20-02    87500.0   35999.870  123499.870
20-03    87500.0   40708.230  128208.230
20-04   166666.0   44833.250  211499.250
20-05   166666.0   58666.510  225332.510
20-06   166666.0   70499.780  237165.780
20-07   175000.0   80583.060  255583.060
20-08   175000.0   89541.440  264541.440
20-09   175000.0   97374.810  272374.810
20-10   208333.0  104249.840  312582.840
20-11   208333.0  114020.655  322353.655
20-12   208333.0  122249.810  330582.810
21-01   208333.0  129728.965  338061.965
21-02   208333.0  139291.445  347624.445
21-03   208333.0  148437.255  356770.255
21-04   416666.0  157249.735  573915.735
21-05   416666.0  195062.175  611728.175
21-06   416666.0  228374.625  645040.625
21-07   291666.0  257520.415  549186.415
21-08   291666.0  263666.210  555332.210
21-09   291666.0  270228.675  561894.675
21-10   250000.0  277207.810  527207.810
21-11   250000.0  277353.715  527353.715
21-12   250000.0  277499.610  527499.610