In [1]:
%load_ext dotenv
%dotenv /home/aurora/.env
%matplotlib inline

In [88]:
import numpy as np
import pandas as pd
import datetime as dt
from google.cloud import bigquery
import re
import pymongo
import os
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from flatten_json import flatten
from tqdm import tqdm
cursor = pymongo.MongoClient("mongodb://" + os.environ['user'] + ':' + 
                             os.environ['pass'] + '@' + os.environ['db1']  + "/?authSource=" + 
                             os.environ['dbname'])
#warnings.filterwarnings('ignore')

In [89]:
# Time
start = dt.datetime(2019,6,25)
end = dt.datetime(2019,6,3)
print(start,end)

2019-06-25 00:00:00 2019-06-03 00:00:00

In [90]:
aw = []
c_users = cursor.superstars.users
for documents in c_users.find({"_id":ObjectId("5d0d1deafa80e3002820af05")}): 
   aw.append(documents)


dic_flattened = [flatten(d) for d in aw]
users = pd.DataFrame(dic_flattened)
aw

NameError: name 'ObjectId' is not defined

In [81]:
users[users['user_id'] == '5d0d1deafa80e3002820af05']

Empty DataFrame
Columns: [user_id, create_time, device_id]
Index: []

In [12]:
users.sort_values(['device_id','create_time'],ascending=False,inplace=True)
users.drop_duplicates('device_id',inplace=True)
print(len(users))
users.head()

26398

,user_id,create_time,device_id
23549,5cf94e14fb3482380005cc3c,2019-06-06 17:32:04.453,ffffc06e7d82cd51683d09a7f3dee2a4
8113,5cd72e3de839226f40a38464,2019-05-11 20:19:09.199,ffff9c0b7fd52ade11feb883aba4134e
7797,5cd708cb112ed13abd410d3f,2019-05-11 17:39:23.137,fffeb1875ef302640a96261a39f30aed
7984,5cd71bd5cfd59d105c9a7213,2019-05-11 19:00:37.963,fff782ca29fe2744d971165f49e885cc
21001,5cf09b210721db1fde85b11a,2019-05-31 03:10:25.629,fff76c9ea9dba2d1721492c6819b8626

In [78]:
team_cursor = cursor.superstars.teams
aw_team = []
for documents in team_cursor.find({},{"user":1,'created_at':1,'name':1}): 
    aw_team.append(documents)
dic_flattened = [flatten(d) for d in aw_team]
teams = pd.DataFrame(dic_flattened)
#teams = teams[teams["user"].isin(users["user_id"])]
teams = teams[["_id","user",'created_at','name']]
teams.columns = ["team_id", "user_id","team_create_time","team_name"]

In [80]:
teams = teams[teams['team_name']=='Dynamic Thunders']
teams

,team_id,user_id,team_create_time,team_name
5026,5ca730af74aaef18f702cdfa,5ca730af74aaef18f702cdd5,2019-04-05 10:40:47.905,Dynamic Thunders
5375,5ca7399fc71a3718d610043f,5ca7399fc71a3718d610041a,2019-04-05 11:18:55.787,Dynamic Thunders
5558,5ca73e9a74aaef18f702e648,5ca73e9a74aaef18f702e623,2019-04-05 11:40:10.132,Dynamic Thunders
6896,5ca762d174aaef18f7031d80,5ca762d174aaef18f7031d5b,2019-04-05 14:14:41.616,Dynamic Thunders
8286,5ca782a3d1d73c10740f3c17,5ca782a3d1d73c10740f3bf2,2019-04-05 16:30:27.495,Dynamic Thunders
9241,5ca7a1c7c8ed5426865077e9,5ca7a1c7c8ed5426865077c4,2019-04-05 18:43:19.331,Dynamic Thunders
11934,5ca85e5e4151d11807139a30,5ca85e5e4151d11807139a0b,2019-04-06 08:07:58.830,Dynamic Thunders
13230,5ca87301786243325020f5a2,5ca87300786243325020f57d,2019-04-06 09:36:01.071,Dynamic Thunders
15480,5ca8a47445bac635cc299e49,5ca8a47445bac635cc299e24,2019-04-06 13:07:00.701,Dynamic Thunders
16781,5ca8c2060c1ce74a2f8486d3,5ca8c2060c1ce74a2f8486ae,2019-04-06 15:13:10.756,Dynamic Thunders
17287,5ca8cbf2f9056b35f30c2e22,5ca8cbf2f9056b35f30c2dfd,2019-04-06 15:55:30.787,Dynamic Thunders
17790,5ca8d71ff8ce984a0ec58ce7,5ca8d71ef8ce984a0ec58cc2,2019-04-06 16:43:11.038,Dynamic Thunders
19282,5ca94f6e0c1ce74a2f852a37,5ca94f6e0c1ce74a2f852a12,2019-04-07 01:16:30.799,Dynamic Thunders
21196,5ca97fb1f8ce984a0ec65cfb,5ca97fb1f8ce984a0ec65cd6,2019-04-07 04:42:25.904,Dynamic Thunders
23088,5ca99fb2fdd1794a28b4be75,5ca99fb2fdd1794a28b4be50,2019-04-07 06:58:58.187,Dynamic Thunders
23932,5ca9ac3c1eeb1935d24a2b52,5ca9ac3c1eeb1935d24a2b2d,2019-04-07 07:52:28.354,Dynamic Thunders
28871,5caa0d961eeb1935d24b4e55,5caa0d961eeb1935d24b4e30,2019-04-07 14:47:50.676,Dynamic Thunders
29099,5caa12a6fdd1794a28b62c10,5caa12a6fdd1794a28b62beb,2019-04-07 15:09:26.204,Dynamic Thunders
32629,5caad8cef9056b35f30fcaf9,5caad8cef9056b35f30fcad4,2019-04-08 05:14:54.720,Dynamic Thunders
33038,5caae5faf9056b35f30fe223,5caae5faf9056b35f30fe1fe,2019-04-08 06:11:06.878,Dynamic Thunders
33125,5caae83745bac635cc2dbf66,5caae83745bac635cc2dbf41,2019-04-08 06:20:39.268,Dynamic Thunders
38216,5cab5f3d3191791bde2c3b8c,5cab5f3d3191791bde2c3b88,2019-04-08 14:48:29.136,Dynamic Thunders
42410,5cac34c50470e3329af19522,5cac34c50470e3329af1951e,2019-04-09 05:59:33.075,Dynamic Thunders
42585,5cac3ac89a66c032c1f04183,5cac3ac89a66c032c1f0417f,2019-04-09 06:25:12.508,Dynamic Thunders
42781,5cac41242609041ff1cfd86c,5cac41242609041ff1cfd868,2019-04-09 06:52:20.308,Dynamic Thunders
42917,5cac45186f3c3a1fa3685c5a,5cac45186f3c3a1fa3685c56,2019-04-09 07:09:12.483,Dynamic Thunders
43055,5cac48f39a66c032c1f0566a,5cac48f39a66c032c1f05666,2019-04-09 07:25:39.258,Dynamic Thunders
44515,5cac66db1f395e1f83315b2f,5cac66db1f395e1f83315b2b,2019-04-09 09:33:15.177,Dynamic Thunders
45447,5cac7a9dea6963452d03b834,5cac7a9dea6963452d03b830,2019-04-09 10:57:33.660,Dynamic Thunders
46102,5cac8bd18d58c44ebec215b4,5cac8bd18d58c44ebec215b0,2019-04-09 12:10:57.639,Dynamic Thunders
...,...,...,...,...
119585,5cd78baf112ed13abd4360e1,5cd78baf112ed13abd4360d9,2019-05-12 02:57:51.832,Dynamic Thunders
121100,5cd7bc560719fb6f18b7bc48,5cd7bc560719fb6f18b7bc40,2019-05-12 06:25:26.176,Dynamic Thunders
124826,5cd81f930719fb6f18bc7716,5cd81f930719fb6f18bc770e,2019-05-12 13:28:51.081,Dynamic Thunders
125131,5cd82c355f50b03a9dd2b133,5cd82c345f50b03a9dd2b12b,2019-05-12 14:22:45.007,Dynamic Thunders
126089,5cd85d255192543ac43a30ac,5cd85d255192543ac43a30a4,2019-05-12 17:51:33.246,Dynamic Thunders
126202,5cd867a90719fb6f18bf46a7,5cd867a90719fb6f18bf469f,2019-05-12 18:36:25.983,Dynamic Thunders
126809,5cd8e3e2af1b883aa37489b5,5cd8e3e2af1b883aa37489ad,2019-05-13 03:26:26.785,Dynamic Thunders
126909,5cd8ed9262ebdd1063870e24,5cd8ed9262ebdd1063870e1c,2019-05-13 04:07:46.081,Dynamic Thunders
127498,5cd928e56d55347e94082979,5cd928e56d55347e94082971,2019-05-13 08:20:53.277,Dynamic Thunders
127692,5cd93eb235e64006b28a9eaa,5cd93eb235e64006b28a9ea2,2019-05-13 09:53:54.339,Dynamic Thunders
128124,5cd995e8b01ed93fb8270e2b,5cd995e8b01ed93fb8270e23,2019-05-13 16:06:00.125,Dynamic Thunders
128178,5cd9a350b0602853007361cf,5cd9a350b0602853007361c7,2019-05-13 17:03:12.329,Dynamic Thunders
129214,5cde1d27c30b6d5aa8f57972,5cde1d27c30b6d5aa8f5796a,2019-05-17 02:32:07.382,Dynamic Thunders
131000,5cef8ec36233545002d909ff,5cef8ec36233545002d909f7,2019-05-30 08:05:23.558,Dynamic Thunders
131031,5cef96b567847c1b7ce35bc1,5cef96b567847c1b7ce35bb9,2019-05-30 08:39:17.772,Dynamic Thunders
131821,5cf0a8f0f588234bcad3d638,5cf0a8f0f588234bcad3d630,2019-05-31 04:09:20.369,Dynamic Thunders
132559,5cf2230ff588234bcae2b0fe,5cf2230ff588234bcae2b0f6,2019-06-01 07:02:39.207,Dynamic Thunders
132594,5cf245047967df1b98914bf8,5cf245047967df1b98914bf0,2019-06-01 09:27:32.336,Dynamic Thunders
135060,5cfb1d54a3a3d57f14c0b52d,NaN,2019-06-08 02:28:36.175,Dynamic Thunders
135163,5cfb5fada3a3d57f14c0b8e7,NaN,2019-06-08 07:11:41.925,Dynamic Thunders
135622,5cfb914aa3a3d57f14c0cdfb,NaN,2019-06-08 10:43:22.958,Dynamic Thunders
137412,5d019b52545afa3b5b548dcd,NaN,2019-06-13 00:39:46.883,Dynamic Thunders
138381,5d0475f918abac35429051a8,NaN,2019-06-15 04:37:13.728,Dynamic Thunders
138834,5d053247f9f1a96059809e58,NaN,2019-06-15 18:00:39.510,Dynamic Thunders
139950,5d0bab83332aa700156340a6,5d0bab83332aa7001563409a,2019-06-20 15:51:31.940,Dynamic Thunders
140089,5d0c97e0c34132001cbcc825,5d0c97e0c34132001cbcc819,2019-06-21 08:40:00.751,Dynamic Thunders
140230,5d0d0c57fa80e300281cfc13,5d0d0c57fa80e300281cfc07,2019-06-21 16:56:55.605,Dynamic Thunders
140252,5d0d1deafa80e3002820af11,5d0d1deafa80e3002820af05,2019-06-21 18:11:54.737,Dynamic Thunders
140374,5d0dd712fa80e300283f29c0,5d0dd712fa80e300283f29b4,2019-06-22 07:21:54.635,Dynamic Thunders
140790,5d0fa5eafa80e3002891760d,5d0fa5eafa80e30028917601,2019-06-23 16:16:42.557,Dynamic Thunders

In [73]:
c_cards = cursor.superstars.user_collectables_logs # this query will give me how many speedup_cards have been used. 
                                                    #Each tap will be counted as one use of the speedup card
aw_cards = []
for documents in c_cards.aggregate([{'$unwind':"$data"}, 
                                    {"$match" : {'data.quantity': {'$lt': 0},
                                                 'type':'HARD_CURRENCY',
                                               
                                                 'data.created_at': {'$gte': start}}}]):
    aw_cards.append(documents)
 
dic_flattened = [flatten(d) for d in aw_cards]
cards = pd.DataFrame(dic_flattened)
# cards = cards[cards["user"].isin(users_team_player_trained['user_id'])]   # total_trained is the number of times each user has trained
# # cards = cards[['user',"data_created_at",'data_catalogue_id']]
# # cards.columns = ['user_id',"event_timestamp",'value']

In [74]:
cards.sort_values('data_quantity',ascending=True,inplace=True)
cards = cards[cards['data_reason_type']=='KIT_KEYS_PURCHASE']
cards.head()

,__v,_id,data__id,data_catalogue_id,data_created_at,data_quantity,data_reason_type,type,user
361,0,5d0d2028fa80e30028215807,5d1211c2fe662b0012acd963,1,2019-06-25 12:21:22.305,-120,KIT_KEYS_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
360,0,5d0d2028fa80e30028215807,5d1211b751a95c001993d949,1,2019-06-25 12:21:11.831,-120,KIT_KEYS_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
358,0,5d0d2028fa80e30028215807,5d12119a51a95c001993cd5a,1,2019-06-25 12:20:42.489,-120,KIT_KEYS_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
355,0,5d0d2028fa80e30028215807,5d12117751a95c001993af54,1,2019-06-25 12:20:07.542,-120,KIT_KEYS_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05
356,0,5d0d2028fa80e30028215807,5d12118351a95c001993b956,1,2019-06-25 12:20:19.151,-120,KIT_KEYS_PURCHASE,HARD_CURRENCY,5d0d1deafa80e3002820af05

In [75]:
a = cards.groupby('user').agg({'data_quantity':'sum'})

In [76]:
a.sort_values('data_quantity',inplace=True)

In [77]:
a

                          data_quantity
user
5d0d1deafa80e3002820af05         -13680
5d11b19afa80e30028e91f8f           -630
5d1188768185c20019d97362           -300
5d131e38114e23001a7aadc9           -120
5d10354ffa80e30028aac20b            -30
5d107a938185c20019accd9d            -30
5d10a7b6fa80e30028be6b40            -30
5d10e7178185c20019c0af35            -30
5d13126b114e23001a77edd5            -30
5d119ce4fa80e30028e61b47            -30
5d0d9f6efa80e30028324b21            -30
5d11cb7cfe662b00129de39d            -30
5d11cf83fe662b00129ff0b5            -30
5d12218b72353600185b2921            -30
5d123a07c5ebf80011829e3d            -30
5d0efc898185c200196a0677            -30
5c97b32e9732f62d3e3adb36            -30